language: ruby
sudo: false
cache: bundler
rvm:
- "2.2.6"
- "2.3.3"
- "2.4.0"
- ruby-head
- jruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
after_script: bundle exec codeclimate-test-reporter
